CREATE TABLE IF NOT EXISTS `forms_ot_visit_discharge_note` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
dischargeplan_Time_In varchar(255),
dischargeplan_Time_Out varchar(255),
dischargeplan_date date,
dischargeplan_Vital_Signs_Pulse varchar(255),
dischargeplan_Vital_Signs_Regular varchar(255),
dischargeplan_Vital_Signs_Irregular varchar(255),
dischargeplan_Vital_Signs_Temperature varchar(255),
dischargeplan_Vital_Signs_Oral varchar(255),
dischargeplan_Vital_Signs_Temporal varchar(255),
dischargeplan_Vital_Signs_other varchar(255),
dischargeplan_Vital_Signs_Respirations varchar(255),
dischargeplan_Vital_Signs_BP_Systolic varchar(255),
dischargeplan_Vital_Signs_BP_Diastolic varchar(255),
dischargeplan_Vital_Signs_Right varchar(255),
dischargeplan_Vital_Signs_Left varchar(255),
dischargeplan_Vital_Signs_Sitting varchar(255),
dischargeplan_Vital_Signs_Standing varchar(255),
dischargeplan_Vital_Signs_Lying varchar(255),
dischargeplan_Vital_Signs_Sat varchar(255),
dischargeplan_Vital_Signs_Pain_Intensity varchar(255),
dischargeplan_Vital_Signs_chronic_condition varchar(255),
dischargeplan_Vital_Signs_Patient_states varchar(255),
dischargeplan_Vital_Signs_Patient_states_other varchar(255),
dischargeplan_treatment_diagnosis_problem varchar(255),
dischargeplan_Mental_Status varchar(255),
dischargeplan_Mental_Status_Other varchar(255),
dischargeplan_Mental_Status_MSS varchar(255),
dischargeplan_Mental_Status_CMT varchar(255), 
dischargeplan_Mental_Status_CCT varchar(255),
dischargeplan_Mental_Status_Other1 varchar(255),
dischargeplan_specific_training_this_visit longtext,
dischargeplan_RfD_No_Further_Skilled varchar(255),
dischargeplan_RfD_Short_Term_Goals varchar(255),
dischargeplan_RfD_Long_Term_Goals varchar(255),
dischargeplan_RfD_Patient_homebound varchar(255),
dischargeplan_RfD_rehab_potential varchar(255),
dischargeplan_RfD_refused_services varchar(255),
dischargeplan_RfD_out_of_service_area varchar(255),
dischargeplan_RfD_Admitted_to_Hospital varchar(255),
dischargeplan_RfD_higher_level_of_care varchar(255),
dischargeplan_RfD_another_Agency varchar(255),
dischargeplan_RfD_Death varchar(255),
dischargeplan_RfD_Transferred_Hospice varchar(255),
dischargeplan_RfD_MD_Request varchar(255),
dischargeplan_RfD_other varchar(255),
dischargeplan_ToD_ADL varchar(255),
dischargeplan_ToD_ADL_notes varchar(255),
dischargeplan_ToD_ADL1 varchar(255),
dischargeplan_ToD_ADL1_notes varchar(255),
dischargeplan_ToD_IADL varchar(255),
dischargeplan_ToD_IADL_notes varchar(255),
dischargeplan_ToD_IADL1 varchar(255),
dischargeplan_ToD_IADL1_notes varchar(255),
dischargeplan_ToD_ROM varchar(255),
dischargeplan_ToD_ROM_in varchar(255),
dischargeplan_ToD_Safety_Management varchar(255),
dischargeplan_ToD_Safety_Management_in varchar(255),
dischargeplan_ToD_Env_Adaptations varchar(255),
dischargeplan_ToD_Env_Adaptations_inc varchar(255),
dischargeplan_ToD_AE_Usage varchar(255),
dischargeplan_ToD_AE_Usage_for varchar(255),
dischargeplan_ToD_CF_Performance varchar(255),
dischargeplan_ToD_CF_Performance_in varchar(255),
dischargeplan_ToD_Per_Home_Exercises varchar(255),
dischargeplan_ToD_Per_Home_Exercises_for varchar(255),
dischargeplan_ToD_Other varchar(255),
dischargeplan_ToD_Status_of_Patient varchar(255),
dischargeplan_Functional_Ability_Timeof_Discharge varchar(255),
dischargeplan_Discharge_anticipated varchar(100),
dischargeplan_Discharge_not_anticipated varchar(100),
dischargeplan_follow_up_treatment varchar(100),
dischargeplan_Recommendations_met varchar(100),
dischargeplan_Recommendations_partially varchar(100),
dischargeplan_Recommendations_not_met varchar(100),
dischargeplan_Recommendations_not_met_note varchar(100),
dischargeplan_md_name varchar(255),
dischargeplan_md_signature varchar(255),
dischargeplan_md_date DATE
) engine=MyISAM;	
