CREATE TABLE IF NOT EXISTS `forms_patient_missed_visit` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

patient_name varchar(100),
patient_mr varchar(100),
patient_missed_date DATE,
descipline_who_category varchar(100),
descipline_who varchar(100),
descipline_who_other varchar(100),
reason_for_category varchar(100),
reason_for varchar(1000),
reason_for_other varchar(100),
actions_taken varchar(1000),
actions_taken_other varchar(100),
patient_need_addressed varchar(500),
patient_need_addressed_other varchar(100),
physician_name varchar(100),
physician_fax_number varchar(100),
physician_acknowledgment varchar(100),
physician_acknowledgment_date DATE,
physician_signature varchar(100),
physician_signature_date DATE,
physician_comments varchar(100)
) ENGINE=MyISAM;	
