CREATE TABLE IF NOT EXISTS `forms_pt_visit_discharge_note` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
dischargeplan_Time_In varchar(100),
dischargeplan_Time_Out varchar(100),
dischargeplan_date date,
dischargeplan_Vital_Signs_Pulse varchar(30),
dischargeplan_Vital_Signs_Pulse_Type varchar(30),
dischargeplan_Vital_Signs_Temperature varchar(30),
dischargeplan_Vital_Signs_Temperature_Type varchar(30),
dischargeplan_Vital_Signs_other varchar(100),
dischargeplan_Vital_Signs_Respirations varchar(30),
dischargeplan_Vital_Signs_BP_Systolic varchar(30),
dischargeplan_Vital_Signs_BP_Diastolic varchar(30),
dischargeplan_Vital_Signs_BP_side varchar(50),
dischargeplan_Vital_Signs_BP_Position varchar(50),
dischargeplan_Vital_Signs_Sat varchar(50),
dischargeplan_Vital_Signs_Pain_Intensity varchar(50),
dischargeplan_Vital_Signs_chronic_condition varchar(50),
dischargeplan_Vital_Signs_Patient_states varchar(30),
dischargeplan_Vital_Signs_Patient_states_other varchar(255),
dischargeplan_treatment_diagnosis_problem varchar(255),
dischargeplan_Mental_Status varchar(100),
dischargeplan_Mental_Status_Other varchar(255),
dischargeplan_specific_training_this_visit longtext,
dischargeplan_RfD_No_Further_Skilled varchar(30),
dischargeplan_RfD_Short_Term_Goals varchar(30),
dischargeplan_RfD_Long_Term_Goals varchar(30),
dischargeplan_RfD_Patient_homebound varchar(30),
dischargeplan_RfD_rehab_potential varchar(30),
dischargeplan_RfD_refused_services varchar(30),
dischargeplan_RfD_out_of_service_area varchar(30),
dischargeplan_RfD_Admitted_to_Hospital varchar(30),
dischargeplan_RfD_higher_level_of_care varchar(30),
dischargeplan_RfD_another_Agency varchar(30),
dischargeplan_RfD_Death varchar(30),
dischargeplan_RfD_Transferred_Hospice varchar(30),
dischargeplan_RfD_MD_Request varchar(30),
dischargeplan_RfD_other varchar(30),
dischargeplan_ToD_Mobility varchar(30),
dischargeplan_ToD_Mobility_Notes text,
dischargeplan_ToD_ROM varchar(30),
dischargeplan_ToD_ROM_In text,
dischargeplan_ToD_Home_Safety_Techniques varchar(30),
dischargeplan_ToD_Home_Safety_Techniques_In varchar(100),
dischargeplan_ToD_Caregiver_Family_Performance varchar(30),
dischargeplan_ToD_Caregiver_Family_Performance_In varchar(100),
dischargeplan_ToD_Demonstrates varchar(30),
dischargeplan_ToD_Demonstrates_Notes varchar(100),
dischargeplan_ToD_Strength varchar(30),
dischargeplan_ToD_Strength_In varchar(100),
dischargeplan_ToD_Assistive_Device_Usage varchar(30),
dischargeplan_ToD_Assistive_Device_Usage_With varchar(100),
dischargeplan_ToD_Performance_of_Home_Exercises varchar(30),
dischargeplan_ToD_Other varchar(255),
dischargeplan_ToD_Discharge_Status_Patient varchar(255),
dischargeplan_Functional_Ability_Timeof_Discharge varchar(255),
dischargeplan_Comments_Recommendations varchar(255),
dischargeplan_Followup_Recommendations text,
dischargeplan_Goals_identified_on_careplan varchar(40),
dischargeplan_Goals_notmet_explanation text,
dischargeplan_Additional_Comments text,
dischargeplan_Therapist_Signature varchar(255),
dischargeplan_md_printed_name varchar(255),
dischargeplan_md_signature varchar(255)
dischargeplan_md_date DATE
) engine=MyISAM;
