CREATE TABLE IF NOT EXISTS `forms_non_oasis` (

id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,


non_oasis_patient varchar(100) DEFAULT NULL,
non_oasis_caregiver varchar(100) DEFAULT NULL,
non_oasis_visit_date datetime DEFAULT NULL,
non_oasis_time_in varchar(40) DEFAULT NULL,
non_oasis_time_out varchar(40) DEFAULT NULL,
non_oasis_pain_weight varchar(20) DEFAULT NULL,
non_oasis_pain_blood_sugar varchar(40) DEFAULT NULL,
non_oasis_pain_bowel varchar(15) DEFAULT NULL,
non_oasis_pain_bowel_other varchar(100) DEFAULT NULL,
non_oasis_pain_bowel_sounds varchar(100) DEFAULT NULL,
non_oasis_pain_bladder varchar(10) DEFAULT NULL,
non_oasis_pain_bladder_other varchar(100) DEFAULT NULL,
non_oasis_pain_urinary_output varchar(80) DEFAULT NULL,
non_oasis_pain_tolerated_procedure varchar(10) DEFAULT NULL,
non_oasis_pain_tolerated_procedure_ot varchar(10) DEFAULT NULL,
non_oasis_pain_tolerated_procedure_other mediumtext,
non_oasis_pain_scale varchar(20) DEFAULT NULL,
non_oasis_pain_location_cause varchar(150) DEFAULT NULL,
non_oasis_pain_description varchar(20) DEFAULT NULL,
non_oasis_pain_frequency varchar(20) DEFAULT NULL,
non_oasis_pain_aggravating_factors varchar(20) DEFAULT NULL,
non_oasis_pain_aggravating_factors_other varchar(50) DEFAULT NULL,
non_oasis_pain_relieving_factors varchar(20) DEFAULT NULL,
non_oasis_pain_relieving_factors_other varchar(50) DEFAULT NULL,
non_oasis_pain_activities_limited varchar(225) DEFAULT NULL,
non_oasis_nutrition_status_prob varchar(20) DEFAULT NULL,
non_oasis_nutrition_status varchar(100) DEFAULT NULL,
non_oasis_nutrition_status_other varchar(225) DEFAULT NULL,
non_oasis_nutrition_requirements varchar(30) DEFAULT NULL,
non_oasis_nutrition_appetite varchar(20) DEFAULT NULL,
non_oasis_nutrition_eat_patt text,
non_oasis_nutrition_eat_patt1 varchar(225) DEFAULT NULL,
non_oasis_nutrition_eat_patt_freq varchar(20) DEFAULT NULL,
non_oasis_nutrition_eat_patt_amt varchar(20) DEFAULT NULL,
non_oasis_nutrition_patt_gain varchar(10) DEFAULT NULL,
non_oasis_nutrition_eat_patt1_gain_time varchar(5) DEFAULT NULL,
non_oasis_nutrition_patt1_other varchar(50) DEFAULT NULL,
non_oasis_nutrition_req varchar(50) DEFAULT NULL,
non_oasis_nutrition_req_other varchar(80) DEFAULT NULL,
non_oasis_nutrition_risks text,
non_oasis_nutrition_risks_MD varchar(50) DEFAULT NULL,
nutrition_total INT DEFAULT '0',
non_oasis_nutrition_describe varchar(100) DEFAULT NULL,
non_oasis_vital_lying_right varchar(20) DEFAULT NULL,
non_oasis_vital_lying_left varchar(20) DEFAULT NULL,
non_oasis_vital_sitting_right varchar(20) DEFAULT NULL,
non_oasis_vital_sitting_left varchar(20) DEFAULT NULL,
non_oasis_vital_standing_right varchar(20) DEFAULT NULL,
non_oasis_vital_standing_left varchar(20) DEFAULT NULL,
non_oasis_vital_temp  varchar(15) DEFAULT NULL,
non_oasis_vital_pulse varchar(80) DEFAULT NULL,
non_oasis_vital_resp_rate varchar(15) DEFAULT NULL,
non_oasis_cardio varchar(15) DEFAULT NULL,
non_oasis_cardio_breath varchar(30) DEFAULT NULL,
non_oasis_cardio_breath1 varchar(150) DEFAULT NULL,
non_oasis_cardio_breath_anterior varchar(30) DEFAULT NULL,
non_oasis_cardio_breath_posterior varchar(30) DEFAULT NULL,
non_oasis_cardio_o2_sat varchar(15) DEFAULT NULL,
non_oasis_cardio_acc_muscles varchar(100) DEFAULT NULL,
non_oasis_cardio_o2 varchar(50) DEFAULT NULL,
non_oasis_cardio_lpm_per varchar(50) DEFAULT NULL,
non_oasis_cardio_trach varchar(5) DEFAULT NULL,
non_oasis_cardio_manages varchar(30) DEFAULT NULL,
non_oasis_cardio_breath_cough varchar(10) DEFAULT NULL,
non_oasis_cardio_breath_productive varchar(10) DEFAULT NULL,
non_oasis_cardio_breath_color varchar(30) DEFAULT NULL,
non_oasis_cardio_breath_amt varchar(10) DEFAULT NULL,
non_oasis_cardio_breath_dyspnea varchar(20) DEFAULT NULL,
non_oasis_cardio_breath_dyspnea_other varchar(100) DEFAULT NULL,
non_oasis_cardio_heart_sounds_type varchar(20) DEFAULT NULL,
non_oasis_cardio_heart_sounds text,
non_oasis_cardio_heart_sounds_pacemaker varchar(50) DEFAULT NULL,
non_oasis_cardio_heart_sounds_pacemaker_date date DEFAULT NULL,
non_oasis_cardio_heart_sounds_pacemaker_type varchar(50) DEFAULT NULL,
non_oasis_cardio_heart_sounds_chest_pain varchar(150) DEFAULT NULL,
non_oasis_cardio_heart_sounds_associated_with varchar(60) DEFAULT NULL,
non_oasis_cardio_heart_sounds_frequency varchar(50) DEFAULT NULL,
non_oasis_cardio_heart_sounds_edema varchar(50) DEFAULT NULL,
non_oasis_cardio_heart_sounds_edema_dependent varchar(100) DEFAULT NULL,
non_oasis_cardio_heart_sounds_site varchar(50) DEFAULT NULL,
non_oasis_cardio_heart_sounds_capillary varchar(50) DEFAULT NULL,
non_oasis_cardio_heart_sounds_other varchar(50) DEFAULT NULL,
non_oasis_cardio_heart_sounds_notify varchar(100) DEFAULT NULL,
non_oasis_braden_scale_sensory INT DEFAULT '0',
non_oasis_braden_scale_moisture INT DEFAULT '0',
non_oasis_braden_scale_activity INT DEFAULT '0',
non_oasis_braden_scale_mobility INT DEFAULT '0',
non_oasis_braden_scale_nutrition INT DEFAULT '0',
non_oasis_braden_scale_friction INT DEFAULT '0',
non_oasis_braden_scale_total INT DEFAULT '0',
non_oasis_wound_lesion_location varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_type varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_status varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_size_length varchar(30) DEFAULT NULL,
non_oasis_wound_lesion_size_width varchar(30) DEFAULT NULL,
non_oasis_wound_lesion_size_depth varchar(30) DEFAULT NULL,
non_oasis_wound_lesion_stage varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_tunneling varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_odor varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_skin varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_edema varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_stoma varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_appearance varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_drainage varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_color varchar(225) DEFAULT NULL,
non_oasis_wound_lesion_consistency varchar(225) DEFAULT NULL,
non_oasis_integumentary_status_problem varchar(15) DEFAULT NULL,
non_oasis_wound_care_done varchar(10) DEFAULT NULL,
non_oasis_wound_location varchar(50) DEFAULT NULL,
non_oasis_wound text,
non_oasis_wound_soiled_dressing_by varchar(50) DEFAULT NULL,
non_oasis_wound_soiled_technique varchar(10) DEFAULT NULL,
non_oasis_wound_cleaned varchar(50) DEFAULT NULL,
non_oasis_wound_irrigated varchar(50) DEFAULT NULL,
non_oasis_wound_packed varchar(50) DEFAULT NULL,
non_oasis_wound_dressing_apply varchar(50) DEFAULT NULL,
non_oasis_wound_incision varchar(50) DEFAULT NULL,
non_oasis_wound_comment varchar(225) DEFAULT NULL,
non_oasis_satisfactory_return_demo varchar(10) DEFAULT NULL,
non_oasis_wound_education varchar(10) DEFAULT NULL,
non_oasis_wound_education_comment varchar(225) DEFAULT NULL,
non_oasis_infusion text,
non_oasis_infusion_peripheral varchar(100) DEFAULT NULL,
non_oasis_infusion_PICC varchar(100) DEFAULT NULL,
non_oasis_infusion_central varchar(20) DEFAULT NULL,
non_oasis_infusion_central_date date DEFAULT NULL,
non_oasis_infusion_xray varchar(10) DEFAULT NULL,
non_oasis_infusion_circum INT DEFAULT '0',
non_oasis_infusion_length INT DEFAULT '0',
non_oasis_infusion_hickman varchar(20) DEFAULT NULL,
non_oasis_infusion_hickman_date date DEFAULT NULL,
non_oasis_infusion_epidural_date date DEFAULT NULL,
non_oasis_infusion_implanted_date date DEFAULT NULL,
non_oasis_infusion_intrathecal_date date DEFAULT NULL,
non_oasis_infusion_med1_admin varchar(50) DEFAULT NULL,
non_oasis_infusion_med1_name varchar(50) DEFAULT NULL,
non_oasis_infusion_med1_dose varchar(50) DEFAULT NULL,
non_oasis_infusion_med1_dilution varchar(50) DEFAULT NULL,
non_oasis_infusion_med1_route varchar(50) DEFAULT NULL,
non_oasis_infusion_med1_frequency varchar(50) DEFAULT NULL,
non_oasis_infusion_med1_duration varchar(50) DEFAULT NULL,
non_oasis_infusion_med2_admin varchar(50) DEFAULT NULL,
non_oasis_infusion_med2_name varchar(50) DEFAULT NULL,
non_oasis_infusion_med2_dose varchar(50) DEFAULT NULL,
non_oasis_infusion_med2_dilution varchar(50) DEFAULT NULL,
non_oasis_infusion_med2_route varchar(50) DEFAULT NULL,
non_oasis_infusion_med2_frequency varchar(50) DEFAULT NULL,
non_oasis_infusion_med2_duration varchar(50) DEFAULT NULL,
non_oasis_infusion_med3_admin varchar(50) DEFAULT NULL,
non_oasis_infusion_med3_name varchar(50) DEFAULT NULL,
non_oasis_infusion_med3_dose varchar(50) DEFAULT NULL,
non_oasis_infusion_med3_dilution varchar(50) DEFAULT NULL,
non_oasis_infusion_med3_route varchar(50) DEFAULT NULL,
non_oasis_infusion_med3_frequency varchar(50) DEFAULT NULL,
non_oasis_infusion_med3_duration varchar(50) DEFAULT NULL,
non_oasis_infusion_pump varchar(50) DEFAULT NULL,
non_oasis_infusion_admin_by varchar(50) DEFAULT NULL,
non_oasis_infusion_admin_by_other varchar(50) DEFAULT NULL,
non_oasis_infusion_purpose text,
non_oasis_infusion_purpose_other varchar(100) DEFAULT NULL,
non_oasis_infusion_care_provided text,
non_oasis_infusion_dressing varchar(20) DEFAULT NULL,
non_oasis_infusion_performed_by varchar(20) DEFAULT NULL,
non_oasis_infusion_frequency varchar(50) DEFAULT NULL,
non_oasis_infusion_injection varchar(50) DEFAULT NULL,
non_oasis_infusion_labs_drawn text,
non_oasis_infusion_interventions text,
non_oasis_enteral varchar(100) DEFAULT NULL,
non_oasis_enteral_other varchar(50) DEFAULT NULL,
non_oasis_enteral_pump varchar(50) DEFAULT NULL,
non_oasis_enteral_feedings varchar(20) DEFAULT NULL,
non_oasis_enteral_rate varchar(50) DEFAULT NULL,
non_oasis_enteral_flush text,
non_oasis_enteral_performed_by varchar(20) DEFAULT NULL,
non_oasis_enteral_performed_by_other varchar(50) DEFAULT NULL,
non_oasis_enteral_dressing text,
non_oasis_enteral_interventions text,
non_oasis_skilled_care varchar(50) DEFAULT NULL,
non_oasis_summary_disciplines varchar(50) DEFAULT NULL,
non_oasis_summary_disciplines_other varchar(50) DEFAULT NULL,
non_oasis_summary_physician varchar(10) DEFAULT NULL,
non_oasis_summary_elsewhere varchar(5) DEFAULT NULL,
non_oasis_summary_reason mediumtext,
non_oasis_summary_medication varchar(50) DEFAULT NULL,
non_oasis_summary_medication_identified mediumtext DEFAULT NULL,
non_oasis_summary_reason_discharge text,
non_oasis_summary_reason_discharge_explain varchar(50) DEFAULT NULL,
non_oasis_summary_reason_discharge_other varchar(80) DEFAULT NULL,
non_oasis_summary_discharge_inst text,
non_oasis_summary_reviewed varchar(80) DEFAULT NULL,
non_oasis_summary_reviewed_other varchar(80) DEFAULT NULL,
non_oasis_summary_immunization varchar(10) DEFAULT NULL,
non_oasis_summary_immun_explain varchar(100) DEFAULT NULL,
non_oasis_summary_written varchar(10) DEFAULT NULL,
non_oasis_summary_written_explain varchar(100) DEFAULT NULL,
non_oasis_summary_demonstrates varchar(10) DEFAULT NULL,
non_oasis_summary_demonstrates_explain varchar(100) DEFAULT NULL,
detail varchar(100),
process varchar(100),
data varchar(100),
label varchar(100)
) ENGINE=MyISAM;
