<?php
include_once("../../globals.php");
include_once("$srcdir/api.inc");
include_once("$srcdir/forms.inc");


if ($encounter == "")
$encounter = date("Ymd");
if ($_GET["mode"] == "new"){
$newid = formSubmit("forms_ot_Reassessment", $_POST, $_GET["id"], $userauthorized);
addForm($encounter, "Reassessment", $newid, "reassessment", $pid, $userauthorized);
}
elseif ($_GET["mode"] == "update") {
sqlInsert("update forms_ot_Reassessment set pid = {$_SESSION["pid"]},groupname='".$_SESSION["authProvider"]."',user='".$_SESSION["authUser"]."',authorized=$userauthorized,activity=1, date = NOW(),
Reassessment_Visit_Count  ='".$_POST["Reassessment_Visit_Count"]."',
Reassessment_Time_In ='".$_POST["Reassessment_Time_In"]."',
Reassessment_Time_Out ='".$_POST["Reassessment_Time_Out"]."',
Reassessment_date  ='".$_POST["Reassessment_date"]."',
Reassessment_Pulse  ='".$_POST["Reassessment_Pulse"]."',
Reassessment_Pulse_State  ='".$_POST["Reassessment_Pulse_State"]."',
Reassessment_Temperature  ='".$_POST["Reassessment_Temperature"]."',
Reassessment_Temperature_type  ='".$_POST["Reassessment_Temperature_type"]."',
Reassessment_VS_other  ='".$_POST["Reassessment_VS_other"]."',
Reassessment_VS_Respirations  ='".$_POST["Reassessment_VS_Respirations"]."',
Reassessment_VS_BP_Systolic  ='".$_POST["Reassessment_VS_BP_Systolic"]."',
Reassessment_VS_BP_Diastolic  ='".$_POST["Reassessment_VS_BP_Diastolic"]."',
Reassessment_VS_BP_Body_side  ='".$_POST["Reassessment_VS_BP_Body_side"]."',
Reassessment_VS_BP_Body_Position  ='".$_POST["Reassessment_VS_BP_Body_Position"]."',
Reassessment_VS_Sat  ='".$_POST["Reassessment_VS_Sat"]."',
Reassessment_VS_Pain  ='".$_POST["Reassessment_VS_Pain"]."',
Reassessment_VS_Pain_Intensity  ='".$_POST["Reassessment_VS_Pain_Intensity"]."',
Reassessment_VS_Pain_Intensity_type  ='".$_POST["Reassessment_VS_Pain_Intensity_type"]."',
Reassessment_VS_Other1  ='".$_POST["Reassessment_VS_Other1"]."',
Reassessment_HR_Needs_assistance  ='".$_POST["Reassessment_HR_Needs_assistance"]."',
Reassessment_HR_Unable_to_leave_home  ='".$_POST["Reassessment_HR_Unable_to_leave_home"]."',
Reassessment_HR_Medical_Restrictions  ='".$_POST["Reassessment_HR_Medical_Restrictions"]."',
Reassessment_HR_Medical_Restrictions_In  ='".$_POST["Reassessment_HR_Medical_Restrictions_In"]."',
Reassessment_HR_SOB_upon_exertion  ='".$_POST["Reassessment_HR_SOB_upon_exertion"]."',
Reassessment_HR_Pain_with_Travel  ='".$_POST["Reassessment_HR_Pain_with_Travel"]."',
Reassessment_HR_Requires_assistance  ='".$_POST["Reassessment_HR_Requires_assistance"]."',
Reassessment_HR_Arrhythmia  ='".$_POST["Reassessment_HR_Arrhythmia"]."',
Reassessment_HR_Bed_Bound  ='".$_POST["Reassessment_HR_Bed_Bound"]."',
Reassessment_HR_Residual_Weakness  ='".$_POST["Reassessment_HR_Residual_Weakness"]."',
Reassessment_HR_Confusion  ='".$_POST["Reassessment_HR_Confusion"]."',
Reassessment_HR_Other  ='".$_POST["Reassessment_HR_Other"]."',
Reassessment_TREATMENT_DX_Problem  ='".$_POST["Reassessment_TREATMENT_DX_Problem"]."',
Reassessment_ADL_Feeding_Initial_Status  ='".$_POST["Reassessment_ADL_Feeding_Initial_Status"]."',
Reassessment_ADL_Feeding_Current_Status  ='".$_POST["Reassessment_ADL_Feeding_Current_Status"]."',
Reassessment_ADL_Feeding_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Feeding_Describe_Mobility_Skills"]."',
Reassessment_ADL_Grooming_Oral_Initial_Status  ='".$_POST["Reassessment_ADL_Grooming_Oral_Initial_Status"]."',
Reassessment_ADL_Grooming_Oral_Current_Status  ='".$_POST["Reassessment_ADL_Grooming_Oral_Current_Status"]."',
Reassessment_ADL_Grooming_Oral_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Grooming_Oral_Describe_Mobility_Skills"]."',
Reassessment_ADL_Toileting_Initial_Status  ='".$_POST["Reassessment_ADL_Toileting_Initial_Status"]."',
Reassessment_ADL_Toileting_Current_Status  ='".$_POST["Reassessment_ADL_Toileting_Current_Status"]."',
Reassessment_ADL_Toileting_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Toileting_Describe_Mobility_Skills"]."',
Reassessment_ADL_Bath_shower_Initial_Status  ='".$_POST["Reassessment_ADL_Bath_shower_Initial_Status"]."',
Reassessment_ADL_Bath_shower_Current_Status  ='".$_POST["Reassessment_ADL_Bath_shower_Current_Status"]."',
Reassessment_ADL_Bath_shower_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Bath_shower_Describe_Mobility_Skills"]."',
Reassessment_ADL_Dressing_UB_LB_Initial_Status  ='".$_POST["Reassessment_ADL_Dressing_UB_LB_Initial_Status"]."',
Reassessment_ADL_Dressing_UB_LB_Current_Status  ='".$_POST["Reassessment_ADL_Dressing_UB_LB_Current_Status"]."',
Reassessment_ADL_Dressing_UB_LB_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Dressing_UB_LB_Describe_Mobility_Skills"]."',
Reassessment_ADL_Functional_Mobility_Initial_Status  ='".$_POST["Reassessment_ADL_Functional_Mobility_Initial_Status"]."',
Reassessment_ADL_Functional_Mobility_Current_Status  ='".$_POST["Reassessment_ADL_Functional_Mobility_Current_Status"]."',
Reassessment_ADL_Functional_Mobility_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Functional_Mobility_Describe_Mobility_Skills"]."',
Reassessment_ADL_Home_Mgt_Initial_Status  ='".$_POST["Reassessment_ADL_Home_Mgt_Initial_Status"]."',
Reassessment_ADL_Home_Mgt_Current_Status  ='".$_POST["Reassessment_ADL_Home_Mgt_Current_Status"]."',
Reassessment_ADL_Home_Mgt_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Home_Mgt_Describe_Mobility_Skills"]."',
Reassessment_ADL_Transportation_Initial_Status  ='".$_POST["Reassessment_ADL_Transportation_Initial_Status"]."',
Reassessment_ADL_Transportation_Current_Status  ='".$_POST["Reassessment_ADL_Transportation_Current_Status"]."',
Reassessment_ADL_Transportation_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_Transportation_Describe_Mobility_Skills"]."',
Reassessment_ADL_STANDING_BALANCE_Initial_Status  ='".$_POST["Reassessment_ADL_STANDING_BALANCE_Initial_Status"]."',
Reassessment_ADL_STANDING_BALANCE_Current_Status  ='".$_POST["Reassessment_ADL_STANDING_BALANCE_Current_Status"]."',
Reassessment_ADL_STANDING_BALANCE_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_STANDING_BALANCE_Describe_Mobility_Skills"]."',
Reassessment_ADL_SITTING_BALANCE_Initial_Status  ='".$_POST["Reassessment_ADL_SITTING_BALANCE_Initial_Status"]."',
Reassessment_ADL_SITTING_BALANCE_Current_Status  ='".$_POST["Reassessment_ADL_SITTING_BALANCE_Current_Status"]."',
Reassessment_ADL_SITTING_BALANCE_Describe_Mobility_Skills  ='".$_POST["Reassessment_ADL_SITTING_BALANCE_Describe_Mobility_Skills"]."',
Reassessment_Assistive_Devices ='".$_POST["Reassessment_Assistive_Devices"]."',
Reassessment_Assistive_Devices_Cane_Type  ='".$_POST["Reassessment_Assistive_Devices_Cane_Type"]."',
Reassessment_Assistive_Devices_Walker_Type  ='".$_POST["Reassessment_Assistive_Devices_Walker_Type"]."',
Reassessment_Assistive_Devices_Other  ='".$_POST["Reassessment_Assistive_Devices_Other"]."',
Reassessment_Timed_Up_Go_Score  ='".$_POST["Reassessment_Timed_Up_Go_Score"]."',
Reassessment_Interpretation_Risk_Types  ='".$_POST["Reassessment_Interpretation_Risk_Types"]."',
Reassessment_Other_Interpretations  ='".$_POST["Reassessment_Other_Interpretations"]."',
Reassessment_Interpretation_NA  ='".$_POST["Reassessment_Interpretation_NA"]."',
Reassessment_Problems_Achieving_Goals  ='".$_POST["Reassessment_Problems_Achieving_Goals"]."',
Reassessment_Environmental_Barriers  ='".$_POST["Reassessment_Environmental_Barriers"]."',
Reassessment_Environmental_Issues_Notes  ='".$_POST["Reassessment_Environmental_Issues_Notes"]."',
Reassessment_Compensatory_Safety_Awareness  ='".$_POST["Reassessment_Compensatory_Safety_Awareness"]."',
Reassessment_Compensatory_Attention_Span   ='".$_POST["Reassessment_Compensatory_Attention_Span"]."',
Reassessment_Compensatory_Short_Term_Memory   ='".$_POST["Reassessment_Compensatory_Short_Term_Memory"]."',
Reassessment_Compensatory_Long_Term_Memory  ='".$_POST["Reassessment_Compensatory_Long_Term_Memory"]."',
Reassessment_Compensatory_For_Vision  ='".$_POST["Reassessment_Compensatory_For_Vision"]."',
Reassessment_Compensatory_For_Hearing  ='".$_POST["Reassessment_Compensatory_For_Hearing"]."',
Reassessment_Compensatory_For_Activity_Tolerance  ='".$_POST["Reassessment_Compensatory_For_Activity_Tolerance"]."',
Reassessment_Compensatory_For_Gross_Motor  ='".$_POST["Reassessment_Compensatory_For_Gross_Motor"]."',
Reassessment_Compensatory_For_Fine_Motor  ='".$_POST["Reassessment_Compensatory_For_Fine_Motor"]."',
Reassessment_Compensatory_For_UseOf_Assistive_Adaptive_Devices  ='".$_POST["Reassessment_Compensatory_For_UseOf_Assistive_Adaptive_Devices"]."',
Reassessment_Compensatory_NA  ='".$_POST["Reassessment_Compensatory_NA"]."',
Reassessment_Compensatory_Problems_Achieving_Goals  ='".$_POST["Reassessment_Compensatory_Problems_Achieving_Goals"]."',
Reassessment_MS_ROM_All_Muscle_WFL  ='".$_POST["Reassessment_MS_ROM_All_Muscle_WFL"]."',
Reassessment_MS_ROM_ALL_ROM_WFL  ='".$_POST["Reassessment_MS_ROM_ALL_ROM_WFL"]."',
Reassessment_MS_ROM_Following_Problem_areas  ='".$_POST["Reassessment_MS_ROM_Following_Problem_areas"]."',
Reassessment_MS_ROM_Problemarea_text  ='".$_POST["Reassessment_MS_ROM_Problemarea_text"]."',
Reassessment_MS_ROM_STRENGTH_Right  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Right"]."',
Reassessment_MS_ROM_STRENGTH_Left  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Left"]."',
Reassessment_MS_ROM_ROM  ='".$_POST["Reassessment_MS_ROM_ROM"]."',
Reassessment_MS_ROM_ROM_Type  ='".$_POST["Reassessment_MS_ROM_ROM_Type"]."',
Reassessment_MS_ROM_Tonicity  ='".$_POST["Reassessment_MS_ROM_Tonicity"]."',
Reassessment_MS_ROM_Further_description  ='".$_POST["Reassessment_MS_ROM_Further_description"]."',
Reassessment_MS_ROM_Problemarea_text1  ='".$_POST["Reassessment_MS_ROM_Problemarea_text1"]."',
Reassessment_MS_ROM_STRENGTH_Right1  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Right1"]."',
Reassessment_MS_ROM_STRENGTH_Left1  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Left1"]."',
Reassessment_MS_ROM_ROM1  ='".$_POST["Reassessment_MS_ROM_ROM1"]."',
Reassessment_MS_ROM_ROM_Type1  ='".$_POST["Reassessment_MS_ROM_ROM_Type1"]."',
Reassessment_MS_ROM_Tonicity1  ='".$_POST["Reassessment_MS_ROM_Tonicity1"]."',
Reassessment_MS_ROM_Further_description1  ='".$_POST["Reassessment_MS_ROM_Further_description1"]."',
Reassessment_MS_ROM_Problemarea_text2  ='".$_POST["Reassessment_MS_ROM_Problemarea_text2"]."',
Reassessment_MS_ROM_STRENGTH_Right2  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Right2"]."',
Reassessment_MS_ROM_STRENGTH_Left2  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Left2"]."',
Reassessment_MS_ROM_ROM2  ='".$_POST["Reassessment_MS_ROM_ROM2"]."',
Reassessment_MS_ROM_ROM_Type2  ='".$_POST["Reassessment_MS_ROM_ROM_Type2"]."',
Reassessment_MS_ROM_Tonicity2  ='".$_POST["Reassessment_MS_ROM_Tonicity2"]."',
Reassessment_MS_ROM_Further_description2  ='".$_POST["Reassessment_MS_ROM_Further_description2"]."',
Reassessment_MS_ROM_Problemarea_text3  ='".$_POST["Reassessment_MS_ROM_Problemarea_text3"]."',
Reassessment_MS_ROM_STRENGTH_Right3  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Right3"]."',
Reassessment_MS_ROM_STRENGTH_Left3  ='".$_POST["Reassessment_MS_ROM_STRENGTH_Left3"]."',
Reassessment_MS_ROM_ROM3  ='".$_POST["Reassessment_MS_ROM_ROM3"]."',
Reassessment_MS_ROM_ROM_Type3  ='".$_POST["Reassessment_MS_ROM_ROM_Type3"]."',
Reassessment_MS_ROM_Tonicity3  ='".$_POST["Reassessment_MS_ROM_Tonicity3"]."',
Reassessment_MS_ROM_Further_description3  ='".$_POST["Reassessment_MS_ROM_Further_description3"]."',
Reassessment_MS_ROM_NA  ='".$_POST["Reassessment_MS_ROM_NA"]."',
Reassessment_MS_ROM_Problems_Achieving_Goals_Type  ='".$_POST["Reassessment_MS_ROM_Problems_Achieving_Goals_Type"]."',
Reassessment_MS_ROM_Problems_Achieving_Goals_Note  ='".$_POST["Reassessment_MS_ROM_Problems_Achieving_Goals_Note"]."',
Reassessment_RO_Patient_Prior_Level_Function  ='".$_POST["Reassessment_RO_Patient_Prior_Level_Function"]."',
Reassessment_RO_Patient_Prior_Level_Function_No1 ='".$_POST["Reassessment_RO_Patient_Prior_Level_Function_No1"]."',
Reassessment_RO_Patient_Prior_Level_Function_No2 ='".$_POST["Reassessment_RO_Patient_Prior_Level_Function_No2"]."',
Reassessment_RO_Patient_Long_Term_Goals  ='".$_POST["Reassessment_RO_Patient_Long_Term_Goals"]."',
Reassessment_Skilled_OT_Reasonable_And_Necessary_To  ='".$_POST["Reassessment_Skilled_OT_Reasonable_And_Necessary_To"]."',
Reassessment_Skilled_OT_Other  ='".$_POST["Reassessment_Skilled_OT_Other"]."',
Reassessment_Goals_Changed_Adapted_For_ADLs  ='".$_POST["Reassessment_Goals_Changed_Adapted_For_ADLs"]."',
Reassessment_Goals_Changed_Adapted_For_ADLs1  ='".$_POST["Reassessment_Goals_Changed_Adapted_For_ADLs1"]."',
Reassessment_Goals_Changed_Adapted_For_IDLs  ='".$_POST["Reassessment_Goals_Changed_Adapted_For_IDLs"]."',
Reassessment_Goals_Changed_Adapted_For_Other  ='".$_POST["Reassessment_Goals_Changed_Adapted_For_Other"]."',
Reassessment_OT_communicated_and_agreed_upon_by  ='".$_POST["Reassessment_OT_communicated_and_agreed_upon_by"]."',
Reassessment_OT_communicated_and_agreed_upon_by_other  ='".$_POST["Reassessment_OT_communicated_and_agreed_upon_by_other"]."',
Reassessment_ADDITIONAL_SERVICES_Home_Exercise  ='".$_POST["Reassessment_ADDITIONAL_SERVICES_Home_Exercise"]."',
Reassessment_ADDITIONAL_SERVICES_Recomme_Env_Adaptations  ='".$_POST["Reassessment_ADDITIONAL_SERVICES_Recomme_Env_Adaptations"]."',
Reassessment_ADDITIONAL_SERVICES_Recomme_SafetyIssues  ='".$_POST["Reassessment_ADDITIONAL_SERVICES_Recomme_SafetyIssues"]."',
Reassessment_ADDITIONAL_SERVICES_Treatment  ='".$_POST["Reassessment_ADDITIONAL_SERVICES_Treatment"]."',
Reassessment_ADDITIONAL_SERVICES_Treatment_for  ='".$_POST["Reassessment_ADDITIONAL_SERVICES_Treatment_for"]."',
Reassessment_Other_Services_Provided  ='".$_POST["Reassessment_Other_Services_Provided"]."',
Reassessment_Therapist_Performing_Reassessment  ='".$_POST["Reassessment_Therapist_Performing_Reassessment"]."',
Reassessment_Therapist_name ='".$_POST["Reassessment_Therapist_name"]."'
where id=$id");
}
$_SESSION["encounter"] = $encounter;
formHeader("Redirecting....");
formJump();
formFooter();

?>
