CREATE TABLE IF NOT EXISTS `forms_home_health` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,


home_health_patient_name varchar(225) DEFAULT NULL,
home_health_patient_hi_claim_no varchar(225) DEFAULT NULL,
home_health_start_care_date varchar(225) DEFAULT NULL,
home_health_cert_period_from DATE default NULL,
home_health_cert_period_to DATE default NULL,
home_health_med_rec_no varchar(225) DEFAULT NULL,
home_health_provider_no varchar(225) DEFAULT NULL,
home_health_patient_name_addr varchar(225) DEFAULT NULL,
home_health_provider_name_addr varchar(225) DEFAULT NULL,
home_health_dob varchar(50) DEFAULT NULL,
home_health_sex varchar(50) DEFAULT NULL,
home_health_icd_9_cm1 varchar(50) DEFAULT NULL,
home_health_principal_diagnosis mediumtext,
home_health_principal_date DATE default NULL,
home_health_principal_eo varchar(225) DEFAULT NULL,
home_health_icd_9_cm2 varchar(50) DEFAULT NULL,
home_health_surgical_procedure mediumtext,
home_health_surgical_date DATE default NULL,
home_health_surgical_eo varchar(225) DEFAULT NULL,
home_health_icd_9_cm3 varchar(50) DEFAULT NULL,
home_health_other_pertinent_diagnosis mediumtext,
home_health_other_date DATE default NULL,
home_health_other_eo varchar(225) DEFAULT NULL,
home_health_medications mediumtext,
home_health_dme_supplies varchar(225) DEFAULT NULL,
home_health_safety_measures varchar(225) DEFAULT NULL,
home_health_nut_reqs varchar(225) DEFAULT NULL,
home_health_allergies varchar(225) DEFAULT NULL,
home_health_functional_limitations text,
home_health_functional_limitations_other varchar(225) DEFAULT NULL,
home_health_activities_permitted text,
home_health_activities_permitted_other varchar(225) DEFAULT NULL,
home_health_mental_status text,
home_health_mental_status_other varchar(225) DEFAULT NULL,
home_health_prognosis varchar(60) DEFAULT NULL,
home_health_orders_discipline mediumtext,
home_health_goals mediumtext,
home_health_nurse_sign varchar(225) DEFAULT NULL,
home_health_nurse_sign_date DATE default NULL,
home_health_date_hha DATE default NULL,
home_health_physician_name_addr mediumtext,
home_health_physician_ph varchar(225) DEFAULT NULL,
home_health_physician_fax varchar(225) DEFAULT NULL,
home_health_physician_npi varchar(225) DEFAULT NULL,
home_health_attending_physician mediumtext,
home_health_attending_physician_date DATE default NULL,
home_health_caregiver_sign varchar(225) DEFAULT NULL

) ENGINE=MyISAM;	
