CREATE TABLE IF NOT EXISTS `forms_st_careplan` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
mr varchar(100),
stdate date,
careplan_ST_intervention varchar(255),
careplan_Treatment_DX varchar(255),
careplan_SOCDate date,
careplan_ST_Decline_in_Oral_Stage_Skills varchar(10),
careplan_ST_Decline_in_Oral_Stage_Skills_Notes varchar(255),
careplan_ST_Decrease_in_Pharyngeal_Stage varchar(10),
careplan_ST_Decrease_in_Pharyngeal_Stage_Note varchar(255), 
careplan_ST_Decline_in_Verbal_Expression varchar(10),
careplan_ST_Decline_in_Verbal_Expression_Note varchar(255), 
careplan_ST_Decline_in_NonVerbal_Expression varchar(10),
careplan_ST_Decline_in_NonVerbal_Expression_Note varchar(255), 
careplan_ST_Decreased_Comprehension varchar(10),
careplan_ST_Decreased_Comprehension_Note varchar(255),
careplan_ST_intervention_Other varchar(255),
careplan_ST_intervention_Other1 varchar(255),
careplan_Treatment_Plan_Frequency varchar(50),
careplan_Treatment_Plan_Duration varchar(50),
careplan_Treatment_Plan_EffectiveDate date,
careplan_Evaluation varchar(10),
careplan_Dysphagia_Compensatory_Strategies varchar(10),
careplan_Swallow_Exercise_Program varchar(10),
careplan_Safety_Training_in_Swallow varchar(10),
careplan_Cognitive_Impairment varchar(10),
careplan_Communication_Strategies varchar(10),
careplan_Cognitive_Compensatory varchar(10),
careplan_Patient_Caregiver_Family_Education varchar(10),
careplan_ST_Other varchar(255),
careplan_ST_Other1 varchar(255),
careplan_STO_Improve_OralStage_skills varchar(10),
careplan_STO_Improve_OralStage_skills_In varchar(100),
careplan_STO_Improve_OralStage_skills_To text,
careplan_STO_Time varchar(100),
careplan_STO_Improve_Pharyngeal_Stage varchar(10),
careplan_STO_Improve_Pharyngeal_Stage_In varchar(40),
careplan_STO_Improve_Pharyngeal_Stage_To text,
careplan_STO_Improve_Verbal_Expression varchar(10),
careplan_STO_Improve_Verbal_Expression_In varchar(100),
careplan_STO_Improve_Verbal_Expression_To text,
careplan_STO_Improve_Non_Verbal_Expression varchar(10),
careplan_STO_Improve_Non_Verbal_Expression_in varchar(10),
careplan_STO_Improve_Non_Verbal_Expression_to varchar(10),
careplan_STO_Improve_careplan_STO_Improve_In varchar(100),
careplan_STO_Improve_careplan_STO_Improve_To text,
careplan_STO_Improve_Improve_Comprehension varchar(10),
careplan_STO_Improve_Improve_Comprehension_In varchar(100),
careplan_STO_Improve_Improve_Comprehension_To text,
careplan_STO_Improve_Caregiver_Family_Performance varchar(10),
careplan_STO_Improve_Caregiver_Family_Performance_In text,
careplan_STO_Other text,
careplan_STO_Other1 text,
careplan_STO_Time1 varchar(100),
careplan_LTO_Return_prior_level_function varchar(10),
careplan_LTO_Return_prior_level_function_In varchar(100),
careplan_LTO_Demonstrate_ability_follow_home_exercise varchar(10),
careplan_LTO_Improve_compensatory_techniques varchar(10),
careplan_LTO_Implement_adaptations varchar(100),
careplan_LTO_Other text,
careplan_LTO_Other_Time varchar(50),
careplan_Rehab_Potential varchar(50),
careplan_DP_When_Goals_Are_Met varchar(40),
careplan_DP_Other text,
careplan_PT_communicated_and_agreed_upon_by varchar(50),
careplan_PT_communicated_and_agreed_upon_Other text,
careplan_Agreeable_to_general_goals varchar(30),
careplan_Highly_motivated_to_improve  varchar(30),
careplan_Supportive_family_caregiver varchar(30),
careplan_Physician_Orders varchar(50),
careplan_May_require_additional_treatment varchar(50),
careplan_May_require_additional_treatment_dueto varchar(255),
careplan_Will_address_above_issues varchar(50),
careplan_Will_address_above_issues_by varchar(255),
careplan_Physician_Orders_Other varchar(255),
careplan_Therapist_Who_Developed_POC varchar(255)
) engine=MyISAM;
