CREATE TABLE IF NOT EXISTS `forms_incident_report` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

incident_report_notes text,
incident_report_caregiver_name varchar(225) DEFAULT NULL,
incident_visit_date date default NULL,
incident_report_patient_name varchar(225) DEFAULT NULL,
incident_report_date date default NULL,
incident_report_occurance_date date default NULL,
incident_report_patient_related text,
incident_report_patient_related_other varchar(225) DEFAULT NULL,
incident_report_description_occurence mediumtext,
incident_report_notifications text,
incident_report_not_physician_name varchar(225) DEFAULT NULL,
incident_report_not_physician_date date default NULL,
incident_report_not_supervisor_name varchar(225) DEFAULT NULL,
incident_report_not_supervisor_date date default NULL,
incident_report_not_caregiver_name varchar(225) DEFAULT NULL,
incident_report_not_caregiver_date date default NULL,
incident_report_not_manager_name varchar(225) DEFAULT NULL,
incident_report_not_manager_date date default NULL,
incident_report_physician_orders varchar(225) DEFAULT NULL,
incident_report_other_actions_taken mediumtext,
incident_report_administrative_review mediumtext,
incident_report_person_filing_report varchar(225) DEFAULT NULL,
incident_report_filing_report_date date default NULL,
incident_report_management_reviewer varchar(225) DEFAULT NULL,
incident_report_management_reviewer_date date default NULL,
incident_report_admin_reviewer varchar(225) DEFAULT NULL,
incident_report_admin_reviewer_date date default NULL,
incident_report_caregiver_sign varchar(225) DEFAULT NULL,
incident_report_caregiver_sign_date date default NULL

) ENGINE=MyISAM;	
