CREATE TABLE IF NOT EXISTS `forms_discharge_summary` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

patient_name varchar(100),
patient_mr varchar(100),
patient_discharge_date DATE,
discharge_summary_discontinue_services text,
discharge_summary_discontinue_services_other varchar(255),
discharge_summary_mental_status varchar(100),
discharge_summary_mental_status_other varchar(255),
discharge_summary_provided_interventions text,
discharge_summary_provided_interventions_other varchar(255),
discharge_summary_discharge_reason mediumtext,
discharge_summary_discharge_reason_other varchar(255),
discharge_summary_functional_ability varchar(150),
discharge_summary_comments_recommendations text,
discharge_summary_service_recommended varchar(100),
discharge_summary_goals_identified varchar(50),
discharge_summary_goals_identified_explanation mediumtext,
discharge_summary_additional_comments mediumtext,
discharge_summary_md_name varchar(100),
discharge_summary_md_signature varchar(100),
discharge_summary_md_signature_date date
) ENGINE=MyISAM;	
