CREATE TABLE IF NOT EXISTS `forms_home_health_aide` (
id bigint(20) NOT NULL auto_increment primary key,
pid bigint(20) default NULL,
date datetime default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

home_health_patient_name varchar(100),
home_health_patient_address varchar(100),
home_health_patient_phone varchar(100),
home_health_care_manager varchar(100),
home_health_aide_visit_frequency varchar(100),
home_health_aide_visit_duration varchar(100),
home_health_aide_visit_effective_date DATE,
patient_problems varchar(100),
home_health_goals_for_care varchar(100),
home_health_goals_for_care_other varchar(100),
home_health_medical_issues varchar(500),
home_health_medical_issues_diet varchar(100),
home_health_medical_issues_allergies varchar(100),
home_health_medical_issues_other varchar(100),
home_health_living_situation varchar(100),
home_health_living_situation_other varchar(100),
home_health_type_of_housing varchar(100),
home_health_type_of_housing_other varchar(100),
home_health_condition_of_housing varchar(100),
home_health_problem_safety_issues varchar(100),
mental_status varchar(100),
mental_status_oriented_to varchar(100),
mental_status_disoriented varchar(100),
impaired_mental_status_requires_resources varchar(100),
impaired_mental_status_requires_resources_other varchar(100),
patient_adl_status varchar(100),
patient_adl_status_other varchar(100),
ambulatory_transfer_status varchar(100),
ambulatory_transfer_status_other varchar(100),
communication_status varchar(100),
communication_status_other varchar(100),
miscellaneous_abilities_hearing varchar(100),
miscellaneous_abilities_vision varchar(100),
miscellaneous_abilities_dentures varchar(100),
home_health_patient_need varchar(1000),
home_health_patient_need_bathing varchar(100),
home_health_patient_need_dressing varchar(100),
home_health_patient_need_haircare varchar(100),
home_health_patient_need_hygiene varchar(100),
home_health_patient_need_mobility varchar(100),
home_health_patient_need_positioning varchar(100),
home_health_patient_need_pressure_location varchar(100),
home_health_patient_need_housekeeping varchar(100),
home_health_patient_need_equipment_care varchar(100),
home_health_patient_need_medication_assist varchar(100),
home_health_patient_need_record_sign varchar(100),
home_health_patient_need_wound_care varchar(100),
additional_instructions varchar(100),
review_date_1 DATE,
signature_1 varchar(100),
review_date_2 DATE,
signature_2 varchar(100),
review_date_3 DATE,
signature_3 varchar(100)
) engine=MyISAM;
