CREATE TABLE `forms_nursing_careplan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `careplan_Assess_Vital_Signs` text,
  `careplan_Assess_Vital_Signs_Specify` text,
  `careplan_SN_Skilled_Assessment_Other` text,
  `careplan_SN_Skilled_Assessment` text,
  `careplan_SN_CARDIO_Assess` text,
  `careplan_SN_CARDIO_Assess_Other` text,
  `careplan_SN_CARDIO_Teach` text,
  `careplan_SN_CARDIO_Teach_Other` text,
  `careplan_SN_CARDIO_Teach_Fluid` varchar(50) DEFAULT NULL,
  careplan_SN_CARDIO_Teach_Complications varchar(200),
  `careplan_SN_CARDIO_PtPcgGoals` text,
  `cardi0_cal1` date DEFAULT NULL,
  `cardi0_cal2` date DEFAULT NULL,
  `cardi0_cal3` date DEFAULT NULL,
  `cardi0_cal4` date DEFAULT NULL,
  `careplan_SN_CARDIO_PtPcgGoals_Other` text,
  `careplan_SN_ENDO_Assess` text,
  `careplan_SN_ENDO_Assess_Hrs` varchar(20) DEFAULT NULL,
  `careplan_SN_ENDO_Admin_Other` varchar(100) DEFAULT NULL,
  `careplan_SN_ENDO_Assess_Suchas` varchar(100) DEFAULT NULL,
  `careplan_SN_ENDO_Assess_Other` text,
  `careplan_SN_ENDO_Teach` text,
  `careplan_SN_ENDO_cal_ada` varchar(50) DEFAULT NULL,
  `careplan_SN_ENDO_Other_Diet` varchar(50) DEFAULT NULL,
  `careplan_SN_ENDO_Perform` text,
  `careplan_SN_ENDO_Perform_Insulin` varchar(30) DEFAULT NULL,
  `careplan_SN_ENDO_Perform_Freq` varchar(30) DEFAULT NULL,
  `careplan_SN_ENDO_Perform_Other` text,
  `careplan_SN_ENDO_PCgGoals` text,
  `careplan_SN_ENDO_PCgGoals_text1` varchar(30) DEFAULT NULL,
  `careplan_SN_ENDO_PCgGoals_Other` text,
  `endo_cal1` date DEFAULT NULL,
  `endo_cal2` date DEFAULT NULL,
  `endo_cal3` date DEFAULT NULL,
  `endo_cal4` date DEFAULT NULL,
  `endo_cal5` date DEFAULT NULL,
  `careplan_SN_GASTRO_Assess` text,
  `careplan_SN_GASTRO_Other` text,
  `careplan_SN_GASTRO_Teach` text,
  `careplan_SN_GASTRO_Suchas` varchar(30) DEFAULT NULL,
  `careplan_SN_GASTRO_Teach_Freq` varchar(30) DEFAULT NULL,
  `careplan_SN_GASTRO_Teach_Other` text,
  `careplan_SN_GASTRO_Perform` text,
  `careplan_SN_GASTRO_Perform_Freq` varchar(30) DEFAULT NULL,
  `careplan_SN_GASTRO_Perform_followup` varchar(30) DEFAULT NULL,
  `careplan_SN_GASTRO_Perform_admin` varchar(30) DEFAULT NULL,
  `careplan_SN_GASTRO_Perform_admin_freq` varchar(30) DEFAULT NULL,
  `careplan_SN_GASTRO_Perform_Other` text,
  `careplan_SN_GASTRO_PcGoals` text,
  `careplan_SN_GASTRO_PcGoals_Other` text,
  `gastro_cal1` date DEFAULT NULL,
  `careplan_SN_GENITO_Assess_Other` text,
  `careplan_SN_GENITO_Assess` text,
  `careplan_SN_GENITO_Teach` text,
  `careplan_SN_GENITO_Teach_Freq` varchar(30) DEFAULT NULL,
  `careplan_SN_GENITO_Teach_Other` text,
  `careplan_SN_GENITO_Perform` text,
  `careplan_SN_GENITO_Perform_size` varchar(20) DEFAULT NULL,
  `careplan_SN_GENITO_Perform_ordered` varchar(20) DEFAULT NULL,
  `careplan_SN_GENITO_Perform_Other` text,
  `careplan_SN_GENITO_PcgGoals` text,
  `genito_cal1` date DEFAULT NULL,
  `genito_cal2` date DEFAULT NULL,
  `genito_cal3` date DEFAULT NULL,
  `genito_cal4` date DEFAULT NULL,
  `careplan_SN_GENITO_PcgGoals_Other` text,
  `careplan_SN_INTEGU_Assess` text,
  `careplan_SN_INTEGU_Assess_Other` text,
  `careplan_SN_INTEGU_Teach` text,
  `careplan_SN_INTEGU_Teach_Other` text,
  `careplan_SN_INTEGU_Perform` varchar(40) DEFAULT NULL,
  `careplan_SN_INTEGU_Perform_location` varchar(30) DEFAULT NULL,
  `careplan_SN_INTEGU_Perform_Freq` varchar(30) DEFAULT NULL,
  `careplan_SN_INTEGU_Perform_Clean` varchar(30) DEFAULT NULL,
  `careplan_SN_INTEGU_Perform_Pack` varchar(30) DEFAULT NULL,
  `careplan_SN_INTEGU_Perform_Apply` varchar(30) DEFAULT NULL,
  `careplan_SN_INTEGU_Perform_Cover` varchar(40) DEFAULT NULL,
  `careplan_SN_INTEGU_Perform_Secure` varchar(50) DEFAULT NULL,
  `careplan_SN_INTEGU_PcgGoals` text,
  `careplan_SN_INTEGU_PcgGoals_areas` varchar(30) DEFAULT NULL,
  `integu_cal1` date DEFAULT NULL,
  `integu_cal2` date DEFAULT NULL,
  `integu_cal3` date DEFAULT NULL,
  `careplan_SN_INTEGU_PcgGoals_Other` text,
  `careplan_SN_MUSCULO_Assess` text,
  `careplan_SN_MUSCULO_Assess_Other` text,
  `careplan_SN_MUSCULO_Teach` text,
  `careplan_SN_MUSCULO_Teach_Other` text,
  `careplan_SN_MUSCULO_Perform_Venipuncture` varchar(50) DEFAULT NULL,
  `careplan_SN_MUSCULO_Perform_staples` varchar(20) DEFAULT NULL,
  `careplan_SN_MUSCULO_Perform_Other` text,
  `careplan_SN_MUSCULO_PcgGoals` text,
  `musculo_cal1` date DEFAULT NULL,
  `musculo_cal2` date DEFAULT NULL,
  `musculo_cal3` date DEFAULT NULL,
  `musculo_cal4` date DEFAULT NULL,
  `careplan_SN_MUSCULO_PcgGoals_Other` text,
  `careplan_SN_MENTAL_Assess` text,
  `careplan_SN_MENTAL_Assess_Other` text,
  `careplan_SN_MENTAL_Teach` text,
  `careplan_SN_MENTAL_Teach_Other` text,
  `careplan_SN_MENTAL_PcgGoals` text,
  `mental_cal1` date DEFAULT NULL,
  `mental_cal2` date DEFAULT NULL,
  `mental_cal3` date DEFAULT NULL,
  `careplan_SN_MENTAL_PcgGoals_Other` text,
  `careplan_SN_NEURO_Assess` text,
  `careplan_SN_NEURO_Assess_minutes` varchar(30) DEFAULT NULL,
  `careplan_SN_NEURO_Assess_Other` text,
  `careplan_SN_NEURO_Teach` text,
  `careplan_SN_NEURO_Teach_Other` text,
  `careplan_SN_NEURO_PcgGoals` text,
  `neuro_cal1` date DEFAULT NULL,
  `neuro_cal2` date DEFAULT NULL,
  `neuro_cal3` date DEFAULT NULL,
  `neuro_cal4` date DEFAULT NULL,
  `neuro_cal5` date DEFAULT NULL,
  `careplan_SN_NEURO_PcgGoals_Other` text,
  `careplan_SN_RESPIR_Assess` text,
  `careplan_SN_RESPIR_Assess_Other` text,
  `careplan_SN_RESPIR_Teach` text,
  `careplan_SN_RESPIR_Teach_Other` text,
  `careplan_SN_RESPIR_Perform` varchar(30) DEFAULT NULL,
  `careplan_SN_RESPIR_Perform_Freq` varchar(30) DEFAULT NULL,
  `careplan_SN_RESPIR_Perform_Other` varchar(100) DEFAULT NULL,
  `careplan_SN_RESPIR_PcgGoals` text,
  `respir_cal1` date DEFAULT NULL,
  `respir_cal2` date DEFAULT NULL,
  `respir_cal3` date DEFAULT NULL,
  `respir_cal4` date DEFAULT NULL,
  `respir_cal5` date DEFAULT NULL,
  `respir_cal6` date DEFAULT NULL,
  `careplan_SN_RESPIR_PcgGoals_Other` text,
  `careplan_SN_GENERAL_Assess` text,
  `careplan_SN_GENERAL_Assess_Other` text,
  `careplan_SN_GENERAL_Teach` text,
  `careplan_SN_GENERAL_Teach_Other` text,
  `careplan_SN_GENERAL_PcgGoals` text,
  `general_cal1` date DEFAULT NULL,
  `general_cal2` date DEFAULT NULL,
  `general_cal3` date DEFAULT NULL,
  `careplan_SN_GENERAL_PcgGoals_Other` text,
  `detail` varchar(100) DEFAULT NULL,
  `label` varchar(100) NOT NULL,
  `process` varchar(100) DEFAULT NULL,
  `data` varchar(100) DEFAULT NULL,
  `wound_value1` text,
  `wound_value2` text,
  `wound_value3` text,
  `wound_value4` text,
  `wound_value5` text,
  `wound_value6` text,
  `wound_value7` text,
  `wound_value8` text,
  `Interventions` text,
  `wound_comments` text,
  `wound_label` text,
  `wound_label2` text,
  `careplan_SN_WC_status` varchar(20) DEFAULT NULL,
  `careplan_SN_provide_wound_care` varchar(30) DEFAULT NULL,
  `careplan_SN_wound_status` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
