CREATE TABLE IF NOT EXISTS `forms_ot_careplan` (
id bigint(20) NOT NULL auto_increment primary key,
pid bigint(20) default NULL,
date datetime default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
mr varchar(20) default NULL,
date_curr date default NULL,
med_dx_icd9 varchar(255),
trmnt_dx_icd9 varchar(255),
SOC_Date date,
adl_skills varchar(255),
adl_skills_text varchar(255),
dec_rom varchar(255),
dec_rom_txt varchar(255),
iadl_skills varchar(255),
iadl_skills_txt varchar(255),
dec_mobility varchar(255),
mobility_in varchar(255),
dec_safety_tech varchar(255),
safety_tech_txt varchar(255),
safety_tech_others1 varchar(255),
safety_tech_others2 varchar(255),
frequency varchar(255),
duration varchar(255),
Freq_Duration1 varchar(100),
Freq_Duration2 varchar(100),
effective_date date default NULL,
evaluation varchar(255),
home_safety varchar(255),
adl_training varchar(255),
iadl_training varchar(255),
visual_comp varchar(255),
energy_copd varchar(255),
orthotics_mgmt varchar(255),
adaptive_equipment varchar(255),
cognitive_comp varchar(255),
homeue_exercise varchar(255),
patient_education varchar(255),
fine_compensatory varchar(255),
educate_safety varchar(255),
teach_bathing_skills varchar(255),
exercises_to_patient varchar(255),
exercises_others varchar(255),
imp_adl_skills varchar(255),
imp_adl_skills_in varchar(255),
imp_adl_skills_to varchar(255),
imp_iadl_skills varchar(255),
imp_iadl_skills_in varchar(255),
imp_iadl_skills_to varchar(255),
wfl_Increase varchar(40),
wfl_details varchar(255),
increase_to varchar(255),
perform varchar(255),
exercise_type varchar(255),
exercise_prompts varchar(255),
improve_safety varchar(255),
safety_technique_in varchar(255),
safety_technique_to varchar(255),
improve_mobility varchar(255),
improve_mobility_in varchar(255),
improve_mobility_to varchar(255),
shortterm_time varchar(100),
shortterm_time1 varchar(100),
shortterm_time2 varchar(100),
shortterm_time3 varchar(100),
shortterm_time4 varchar(100),
shortterm_time5 varchar(100),
shortterm_time6 varchar(100),
shortterm_time7 varchar(100),
time_others1 varchar(255),
time_others2 varchar(255),
time_others3 varchar(255),
return_to_priorlevel varchar(255),
return_priorlevel_in varchar(255),
longterm_time varchar(100),
longterm_time1 varchar(100),
longterm_time2 varchar(100),
longterm_time3 varchar(100),
longterm_time4 varchar(100),
home_exercise varchar(255),
safety_at_home varchar(255),
envrn_changes_home varchar(255),
longterm_others varchar(255),
rehabpotential varchar(100),
rehabpotential_goals_met varchar(10),
rehabpotential_others varchar(100),
careplan_discharge_comm varchar(100),
care_plan_discharge_other varchar(100),
careplan_response_agree varchar(100),
careplan_response_motivated varchar(100),
careplan_response_supp varchar(100),
addtn_treatment varchar(100),
addtn_treatment_req varchar(100),
physician_orders_obtained varchar(255),
physician_orders_needed varchar(255),
address_issues_by varchar(100),
address_issues_options varchar(255),
address_issues_others varchar(255),
additional_comments_text text,
therapist_name varchar(255)
) engine=MyISAM;
