CREATE TABLE IF NOT EXISTS `forms_msw_careplan` (
id bigint(20) NOT NULL auto_increment primary key,
pid bigint(20) default NULL,
date datetime default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

SOC_date DATE,
problem_reason_for_referel varchar(100),
spouse_significant_others_row1 varchar(500),
spouse_significant_others_row2 varchar(500),
spouse_significant_others_row3 varchar(500),
caregivers_row1 varchar(500),
caregivers_row2 varchar(500),
patient_lives varchar(100),
patient_lives_with_who varchar(100),
patient_lives_other varchar(100),
no_of_hours_patient_alone varchar(100),
type_of_housing varchar(100),
type_of_housing_other varchar(100),
condition_of_housing varchar(100),
problem_safety_issues varchar(100),
mental_status varchar(100),
mental_status_oriented_to varchar(100),
mental_status_disoriented varchar(100),
impaired_mental_status_requires_resources varchar(100),
impaired_mental_status_requires_resources_other varchar(100),
patient_adl_status varchar(100),
patient_adl_status_other varchar(100),
ambulatory_transfer_status varchar(100),
ambulatory_transfer_status_other varchar(100),
communication_status varchar(100),
communication_status_other varchar(100),
miscellaneous_abilities_hearing varchar(100),
miscellaneous_abilities_hearing_other varchar(100),
miscellaneous_abilities_vision varchar(100),
miscellaneous_abilities_vision_other varchar(100),
patient_needs_help_with varchar(255),
patient_needs_help_with_other varchar(100),
patient_desired varchar(255),
short_term_time_frame varchar(255),
long_term_time_frame varchar(255),
SOC_date2 DATE,
medical_social_services_interventions varchar(1000),
medical_social_services_interventions_other varchar(100),
analysis_of_finding varchar(255),
review_of_interventions varchar(255),
evaluation_of_patient varchar(255),
continued_treatmentplan_frequency varchar(100),
continued_treatmentplan_duration varchar(100),
continued_treatmentplan_effective_date DATE,
msw_careplan_communicated_agreed varchar(100),
msw_careplan_communicated_agreed_other varchar(100),
physician_order varchar(255),
other_comments varchar(100)
) engine=MyISAM;
