CREATE TABLE IF NOT EXISTS `forms_supervisor_visit_note` (
id bigint(20) NOT NULL auto_increment primary key,
pid bigint(20) default NULL,
date datetime default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

patient_name varchar(100),
time_in varchar(100),
time_out varchar(100),
SOC_date DATE,
staff_supervised varchar(100),
supervisor_visits varchar(100),
reported_to_patient_home varchar(100),
wearing_name_badge varchar(100),
using_two_identifiers varchar(100),
demonstrates_behaviour varchar(100),
follow_home_health varchar(100),
demonstrates_communication varchar(100),
aware_patient_code varchar(100),
demonstrates_clinical_skills varchar(100),
adheres_to_policies varchar(100),
identify_patient_issues varchar(100),
handling_skills varchar(100),
demonstrates_grooming varchar(100),
supervisor_visit_other varchar(100),
additional_notes varchar(100),
clinician_signature varchar(100),
clinician_signature_date DATE
) engine=MyISAM;
