<?php
include_once("../../globals.php");
include_once("$srcdir/api.inc");
include_once("$srcdir/forms.inc");

$addnew = array();
foreach($_POST as $key => $val) {
	if(is_array($val)) { $val = implode("#",$val); }
	$addnew[$key] = $val;
}

if ($encounter == "")
$encounter = date("Ymd");
if ($_GET["mode"] == "new"){




$newid = formSubmit("forms_oasis_adult_assessment", $addnew, $_GET["id"], $userauthorized);
addForm($encounter, "ADULT ASSESSMENT", $newid,'oasis_adult_assessment', $pid, $userauthorized);
}
elseif ($_GET["mode"] == "update") {

sqlInsert("update forms_oasis_adult_assessment set pid = {$_SESSION["pid"]},groupname='".$_SESSION["authProvider"]."',
user='".$_SESSION["authUser"]."',authorized=$userauthorized,activity=1, date = NOW(),
detail ='".$_POST["detail"]."',
label ='".$_POST["label"]."',
process ='".$_POST["process"]."',
data ='".$_POST["data"]."',
oasis_patient ='".$_POST["oasis_patient"]."',
oasis_caregiver ='".$_POST["oasis_caregiver"]."',
oasis_visit_date ='".$_POST["oasis_visit_date"]."',
oasis_Time_In ='".$_POST["oasis_Time_In"]."',
oasis_Time_Out ='".$_POST["oasis_Time_Out"]."',
oasis_certification_period_from ='".$_POST["oasis_certification_period_from"]."',
oasis_certification_period_to ='".$_POST["oasis_certification_period_to"]."',
oasisAdultAssess_Heath_Insurance_Claim ='".$_POST["oasisAdultAssess_Heath_Insurance_Claim"]."',
oasis_physician_last_contacted ='".$_POST["oasis_physician_last_contacted"]."',
oasis_physician_last_visited ='".$_POST["oasis_physician_last_visited"]."',
oasis_primary_reason_home_health ='".$_POST["oasis_primary_reason_home_health"]."',
oasis_treat_patient_illness ='".$_POST["oasis_treat_patient_illness"]."',
oasis_treat_patient_illness_other ='".$_POST["oasis_treat_patient_illness_other"]."',
oasis_treat_patient_illness_other_text ='".$_POST["oasis_treat_patient_illness_other_text"]."',
oasis_patient_history_previous_outcomes ='".implode("#",$_POST["oasis_patient_history_previous_outcomes"])."',
oasis_patient_history_previous_outcomes_site ='".$_POST["oasis_patient_history_previous_outcomes_site"]."',
oasis_patient_history_previous_outcomes_other ='".$_POST["oasis_patient_history_previous_outcomes_other"]."',
oasis_prior_hospitalizations ='".$_POST["oasis_prior_hospitalizations"]."',
oasis_prior_hospitalizations_times ='".$_POST["oasis_prior_hospitalizations_times"]."',
oasis_prior_hospitalizations_Reason1 ='".$_POST["oasis_prior_hospitalizations_Reason1"]."',
oasis_prior_hospitalizations_date1 ='".$_POST["oasis_prior_hospitalizations_date1"]."',
oasis_prior_hospitalizations_Reason2 ='".$_POST["oasis_prior_hospitalizations_Reason2"]."',
oasis_prior_hospitalizations_date2 ='".$_POST["oasis_prior_hospitalizations_date2"]."',
oasis_immunizations ='".$_POST["oasis_immunizations"]."',
oasis_immunizations_needs ='".implode("#",$_POST["oasis_immunizations_needs"])."',
oasis_immunizations_needs_other ='".$_POST["oasis_immunizations_needs_other"]."',
oasis_allergies ='".implode("#",$_POST["oasis_allergies"])."',
oasis_allergies_other ='".$_POST["oasis_allergies_other"]."',
oasis_prognosis ='".$_POST["oasis_prognosis"]."',
oasis_advance_directives ='".implode("#",$_POST["oasis_advance_directives"])."',
oasis_patient_family_informed ='".$_POST["oasis_patient_family_informed"]."',
oasis_patient_family_informed_explain ='".$_POST["oasis_patient_family_informed_explain"]."',
oasis_safety_measures ='".implode("#",$_POST["oasis_safety_measures"])."',
oasis_safety_measures_other ='".$_POST["oasis_safety_measures_other"]."',
oasis_sanitation_hazards ='".implode("#",$_POST["oasis_sanitation_hazards"])."',
oasis_sanitation_hazards_other ='".$_POST["oasis_sanitation_hazards_other"]."',
oasis_safety_fire ='".$_POST["oasis_safety_fire"]."',
oasis_safety_smoke ='".$_POST["oasis_safety_smoke"]."',
oasis_safety_tested ='".$_POST["oasis_safety_tested"]."',
oasis_safety_one_exit ='".$_POST["oasis_safety_one_exit"]."',
oasis_safety_plan_exit ='".$_POST["oasis_safety_plan_exit"]."',
oasis_safety_plan_power ='".$_POST["oasis_safety_plan_power"]."',
oasis_safety_signs_posted ='".$_POST["oasis_safety_signs_posted"]."',
oasis_safety_handles_smoking ='".$_POST["oasis_safety_handles_smoking"]."',
oasis_safety_oxygen_backup ='".implode("#",$_POST["oasis_safety_oxygen_backup"])."',
oasis_safety_hazards ='".implode("#",$_POST["oasis_safety_hazards"])."',
oasis_safety_hazards_other ='".$_POST["oasis_safety_hazards_other"]."',
oasis_patient_history_caregiver ='".$_POST["oasis_patient_history_caregiver"]."',
oasis_caregiver_relationship ='".$_POST["oasis_caregiver_relationship"]."',
oasis_caregiver_phonenumber ='".$_POST["oasis_caregiver_phonenumber"]."',
oasis_language_spoken ='".implode("#",$_POST["oasis_language_spoken"])."',
oasis_language_spoken_other ='".$_POST["oasis_language_spoken_other"]."',
oasis_patient_history_commnets ='".$_POST["oasis_patient_history_commnets"]."',
oasis_able_to_care ='".$_POST["oasis_able_to_care"]."',
oasis_able_to_care_reason ='".$_POST["oasis_able_to_care_reason"]."',
oasis_functional_limitations ='".implode("#",$_POST["oasis_functional_limitations"])."',
oasis_functional_limitations_other ='".$_POST["oasis_functional_limitations_other"]."',
oasis_musculoskeletal ='".implode("#",$_POST["oasis_musculoskeletal"])."',
oasis_musculoskeletal_fracture_location ='".$_POST["oasis_musculoskeletal_fracture_location"]."',
oasis_musculoskeletal_swollen ='".$_POST["oasis_musculoskeletal_swollen"]."',
oasis_musculoskeletal_contractures_joint ='".$_POST["oasis_musculoskeletal_contractures_joint"]."',
oasis_musculoskeletal_Amputation ='".$_POST["oasis_musculoskeletal_Amputation"]."',
oasis_musculoskeletal_other ='".$_POST["oasis_musculoskeletal_other"]."',
oasis_vision ='".implode("#",$_POST["oasis_vision"])."',
oasis_vision_cataract_surgery ='".$_POST["oasis_vision_cataract_surgery"]."',
oasis_vision_date ='".$_POST["oasis_vision_date"]."',
oasis_vision_other ='".$_POST["oasis_vision_other"]."',
oasis_nose ='".implode("#",$_POST["oasis_nose"])."',
oasis_nose_other ='".$_POST["oasis_nose_other"]."',
oasis_ear ='".implode("#",$_POST["oasis_ear"])."',
oasis_ear_other ='".$_POST["oasis_ear_other"]."',
oasis_mouth ='".implode("#",$_POST["oasis_mouth"])."',
oasis_mouth_other ='".$_POST["oasis_mouth_other"]."',
oasis_throat ='".implode("#",$_POST["oasis_throat"])."',
oasis_throat_other ='".$_POST["oasis_throat_other"]."',
oasis_vital_lying_right  = '".$_POST["oasis_vital_lying_right"]."',
oasis_vital_lying_left  = '".$_POST["oasis_vital_lying_left"]."',
oasis_vital_sitting_right  = '".$_POST["oasis_vital_sitting_right"]."',
oasis_vital_sitting_left  = '".$_POST["oasis_vital_sitting_left"]."',
oasis_vital_standing_right  = '".$_POST["oasis_vital_standing_right"]."',
oasis_vital_standing_left  = '".$_POST["oasis_vital_standing_left"]."',
oasis_vital_temp  = '".$_POST["oasis_vital_temp"]."',
oasis_vital_pulse  = '".implode("#",$_POST["oasis_vital_pulse"])."',
oasis_vital_resp_rate  = '".$_POST["oasis_vital_resp_rate"]."',
oasis_height = '".$_POST["oasis_height"]."',
oasis_height_check = '".$_POST["oasis_height_check"]."',
oasis_weight = '".$_POST["oasis_weight"]."',
oasis_weight_check = '".$_POST["oasis_weight_check"]."',
oasis_weight_changes = '".$_POST["oasis_weight_changes"]."',
oasis_weight_changes_yes = '".$_POST["oasis_weight_changes_yes"]."',
oasis_weight_gain = '".$_POST["oasis_weight_gain"]."',
oasis_weight_loss = '".$_POST["oasis_weight_loss"]."',
oasis_weight_changes_yes_lbin = '".$_POST["oasis_weight_changes_yes_lbin"]."',
oasis_pain_scale  = '".$_POST["oasis_pain_scale"]."',
oasis_pain_location_cause  = '".$_POST["oasis_pain_location_cause"]."',
oasis_pain_description  = '".$_POST["oasis_pain_description"]."',
oasis_pain_frequency  = '".$_POST["oasis_pain_frequency"]."',
oasis_pain_aggravating_factors  = '".$_POST["oasis_pain_aggravating_factors"]."',
oasis_pain_aggravating_factors_other  = '".$_POST["oasis_pain_aggravating_factors_other"]."',
oasis_pain_relieving_factors  = '".implode("#",$_POST["oasis_pain_relieving_factors"])."',
oasis_pain_relieving_factors_other  = '".$_POST["oasis_pain_relieving_factors_other"]."',
oasis_pain_activities_limited  = '".$_POST["oasis_pain_activities_limited"]."',
oasis_pain_experiencing = '".$_POST["oasis_pain_experiencing"]."',
oasis_pain_unable_communicate = '".$_POST["oasis_pain_unable_communicate"]."',
oasis_pain_non_verbals = '".implode("#",$_POST["oasis_pain_non_verbals"])."',
oasis_pain_non_verbals_other = '".$_POST["oasis_pain_non_verbals_other"]."',
oasis_pain_non_verbals_implications = '".$_POST["oasis_pain_non_verbals_implications"]."',
oasis_pain_breakthrough_medication = '".$_POST["oasis_pain_breakthrough_medication"]."',
oasis_pain_breakthrough_medication_other = '".$_POST["oasis_pain_breakthrough_medication_other"]."',
oasis_pain_breakthrough_implication  = '".$_POST["oasis_pain_breakthrough_implication"]."',
oasis_go_test_trail1 = '".$_POST["oasis_go_test_trail1"]."',
oasis_go_test_trail2 = '".$_POST["oasis_go_test_trail2"]."',
oasis_go_test_avg = '".$_POST["oasis_go_test_avg"]."',
oasis_integumentary_status_conditions = '".implode("#",$_POST["oasis_integumentary_status_conditions"])."',
oasis_integumentary_status_conditions_other = '".$_POST["oasis_integumentary_status_conditions_other"]."',
oasis_braden_scale_sensory  = '".$_POST["oasis_braden_scale_sensory"]."',
oasis_braden_scale_moisture  = '".$_POST["oasis_braden_scale_moisture"]."',
oasis_braden_scale_activity  = '".$_POST["oasis_braden_scale_activity"]."',
oasis_braden_scale_mobility  = '".$_POST["oasis_braden_scale_mobility"]."',
oasis_braden_scale_nutrition  = '".$_POST["oasis_braden_scale_nutrition"]."',
oasis_braden_scale_friction  = '".$_POST["oasis_braden_scale_friction"]."',
oasis_braden_scale_total  = '".$_POST["oasis_braden_scale_total"]."',
oasis_integumentary_status_problem  = '".$_POST["oasis_integumentary_status_problem"]."',
oasis_wound_care_done  = '".$_POST["oasis_wound_care_done"]."',
oasis_wound_location  = '".$_POST["oasis_wound_location"]."',
oasis_wound  = '".implode("#",$_POST["oasis_wound"])."',
oasis_wound_soiled_dressing_by  = '".$_POST["oasis_wound_soiled_dressing_by"]."',
oasis_wound_soiled_technique  = '".$_POST["oasis_wound_soiled_technique"]."',
oasis_wound_cleaned  = '".$_POST["oasis_wound_cleaned"]."',
oasis_wound_irrigated  = '".$_POST["oasis_wound_irrigated"]."',
oasis_wound_packed  = '".$_POST["oasis_wound_packed"]."',
oasis_wound_dressing_apply  = '".$_POST["oasis_wound_dressing_apply"]."',
oasis_wound_incision  = '".$_POST["oasis_wound_incision"]."',
oasis_wound_comment  = '".$_POST["oasis_wound_comment"]."',
oasis_satisfactory_return_demo  = '".$_POST["oasis_satisfactory_return_demo"]."',
oasis_wound_education  = '".$_POST["oasis_wound_education"]."',
oasis_wound_education_comment  = '".$_POST["oasis_wound_education_comment"]."',
oasis_wound_lesion_location  = '".implode("#",$_POST["oasis_wound_lesion_location"])."',
oasis_wound_lesion_type  = '".implode("#",$_POST["oasis_wound_lesion_type"])."',
oasis_wound_lesion_status  = '".implode("#",$_POST["oasis_wound_lesion_status"])."',
oasis_wound_lesion_size_length  = '".implode("#",$_POST["oasis_wound_lesion_size_length"])."',
oasis_wound_lesion_size_width  = '".implode("#",$_POST["oasis_wound_lesion_size_width"])."',
oasis_wound_lesion_size_depth  = '".implode("#",$_POST["oasis_wound_lesion_size_depth"])."',
oasis_wound_lesion_stage  = '".implode("#",$_POST["oasis_wound_lesion_stage"])."',
oasis_wound_lesion_tunneling  = '".implode("#",$_POST["oasis_wound_lesion_tunneling"])."',
oasis_wound_lesion_odor  = '".implode("#",$_POST["oasis_wound_lesion_odor"])."',
oasis_wound_lesion_skin  = '".implode("#",$_POST["oasis_wound_lesion_skin"])."',
oasis_wound_lesion_edema  = '".implode("#",$_POST["oasis_wound_lesion_edema"])."',
oasis_wound_lesion_stoma  = '".implode("#",$_POST["oasis_wound_lesion_stoma"])."',
oasis_wound_lesion_appearance  = '".implode("#",$_POST["oasis_wound_lesion_appearance"])."',
oasis_wound_lesion_drainage  = '".implode("#",$_POST["oasis_wound_lesion_drainage"])."',
oasis_wound_lesion_color  = '".implode("#",$_POST["oasis_wound_lesion_color"])."',
oasis_wound_lesion_consistency  = '".implode("#",$_POST["oasis_wound_lesion_consistency"])."',
oasis_patient_diagnosis_1a='".$_POST["oasis_patient_diagnosis_1a"]."',
oasis_patient_diagnosis_2a='".$_POST["oasis_patient_diagnosis_2a"]."',
oasis_patient_diagnosis_2a_sub='".$_POST["oasis_patient_diagnosis_2a_sub"]."',
oasis_patient_diagnosis_3a='".$_POST["oasis_patient_diagnosis_3a"]."',
oasis_patient_diagnosis_4a='".$_POST["oasis_patient_diagnosis_4a"]."',
oasis_patient_diagnosis_1b='".$_POST["oasis_patient_diagnosis_1b"]."',
oasis_patient_diagnosis_2b='".$_POST["oasis_patient_diagnosis_2b"]."',
oasis_patient_diagnosis_2b_sub='".$_POST["oasis_patient_diagnosis_2b_sub"]."',
oasis_patient_diagnosis_3b='".$_POST["oasis_patient_diagnosis_3b"]."',
oasis_patient_diagnosis_4b='".$_POST["oasis_patient_diagnosis_4b"]."',
oasis_patient_diagnosis_1c='".$_POST["oasis_patient_diagnosis_1c"]."',
oasis_patient_diagnosis_2c='".$_POST["oasis_patient_diagnosis_2c"]."',
oasis_patient_diagnosis_2c_sub='".$_POST["oasis_patient_diagnosis_2c_sub"]."',
oasis_patient_diagnosis_3c='".$_POST["oasis_patient_diagnosis_3c"]."',
oasis_patient_diagnosis_4c='".$_POST["oasis_patient_diagnosis_4c"]."',
oasis_patient_diagnosis_1d='".$_POST["oasis_patient_diagnosis_1d"]."',
oasis_patient_diagnosis_2d='".$_POST["oasis_patient_diagnosis_2d"]."',
oasis_patient_diagnosis_2d_sub='".$_POST["oasis_patient_diagnosis_2d_sub"]."',
oasis_patient_diagnosis_3d='".$_POST["oasis_patient_diagnosis_3d"]."',
oasis_patient_diagnosis_4d='".$_POST["oasis_patient_diagnosis_4d"]."',
oasis_patient_diagnosis_1e='".$_POST["oasis_patient_diagnosis_1e"]."',
oasis_patient_diagnosis_2e='".$_POST["oasis_patient_diagnosis_2e"]."',
oasis_patient_diagnosis_2e_sub='".$_POST["oasis_patient_diagnosis_2e_sub"]."',
oasis_patient_diagnosis_3e='".$_POST["oasis_patient_diagnosis_3e"]."',
oasis_patient_diagnosis_4e='".$_POST["oasis_patient_diagnosis_4e"]."',
oasis_patient_diagnosis_1f='".$_POST["oasis_patient_diagnosis_1f"]."',
oasis_patient_diagnosis_2f='".$_POST["oasis_patient_diagnosis_2f"]."',
oasis_patient_diagnosis_2f_sub='".$_POST["oasis_patient_diagnosis_2f_sub"]."',
oasis_patient_diagnosis_3f='".$_POST["oasis_patient_diagnosis_3f"]."',
oasis_patient_diagnosis_4f='".$_POST["oasis_patient_diagnosis_4f"]."',
oasis_patient_diagnosis_1g='".$_POST["oasis_patient_diagnosis_1g"]."',
oasis_patient_diagnosis_2g='".$_POST["oasis_patient_diagnosis_2g"]."',
oasis_patient_diagnosis_2g_sub='".$_POST["oasis_patient_diagnosis_2g_sub"]."',
oasis_patient_diagnosis_3g='".$_POST["oasis_patient_diagnosis_3g"]."',
oasis_patient_diagnosis_4g='".$_POST["oasis_patient_diagnosis_4g"]."',
oasis_patient_diagnosis_1h='".$_POST["oasis_patient_diagnosis_1h"]."',
oasis_patient_diagnosis_2h='".$_POST["oasis_patient_diagnosis_2h"]."',
oasis_patient_diagnosis_2h_sub='".$_POST["oasis_patient_diagnosis_2h_sub"]."',
oasis_patient_diagnosis_3h='".$_POST["oasis_patient_diagnosis_3h"]."',
oasis_patient_diagnosis_4h='".$_POST["oasis_patient_diagnosis_4h"]."',
oasis_patient_diagnosis_1i='".$_POST["oasis_patient_diagnosis_1i"]."',
oasis_patient_diagnosis_2i='".$_POST["oasis_patient_diagnosis_2i"]."',
oasis_patient_diagnosis_2i_sub='".$_POST["oasis_patient_diagnosis_2i_sub"]."',
oasis_patient_diagnosis_3i='".$_POST["oasis_patient_diagnosis_3i"]."',
oasis_patient_diagnosis_4i='".$_POST["oasis_patient_diagnosis_4i"]."',
oasis_patient_diagnosis_1j='".$_POST["oasis_patient_diagnosis_1j"]."',
oasis_patient_diagnosis_2j='".$_POST["oasis_patient_diagnosis_2j"]."',
oasis_patient_diagnosis_2j_sub='".$_POST["oasis_patient_diagnosis_2j_sub"]."',
oasis_patient_diagnosis_3j='".$_POST["oasis_patient_diagnosis_3j"]."',
oasis_patient_diagnosis_4j='".$_POST["oasis_patient_diagnosis_4j"]."',
oasis_patient_diagnosis_1k='".$_POST["oasis_patient_diagnosis_1k"]."',
oasis_patient_diagnosis_2k='".$_POST["oasis_patient_diagnosis_2k"]."',
oasis_patient_diagnosis_2k_sub='".$_POST["oasis_patient_diagnosis_2k_sub"]."',
oasis_patient_diagnosis_3k='".$_POST["oasis_patient_diagnosis_3k"]."',
oasis_patient_diagnosis_4k='".$_POST["oasis_patient_diagnosis_4k"]."',
oasis_patient_diagnosis_1l='".$_POST["oasis_patient_diagnosis_1l"]."',
oasis_patient_diagnosis_2l='".$_POST["oasis_patient_diagnosis_2l"]."',
oasis_patient_diagnosis_2l_sub='".$_POST["oasis_patient_diagnosis_2l_sub"]."',
oasis_patient_diagnosis_3l='".$_POST["oasis_patient_diagnosis_3l"]."',
oasis_patient_diagnosis_4l='".$_POST["oasis_patient_diagnosis_4l"]."',
oasis_patient_diagnosis_1m='".$_POST["oasis_patient_diagnosis_1m"]."',
oasis_patient_diagnosis_2m='".$_POST["oasis_patient_diagnosis_2m"]."',
oasis_patient_diagnosis_2m_sub='".$_POST["oasis_patient_diagnosis_2m_sub"]."',
oasis_patient_diagnosis_3m='".$_POST["oasis_patient_diagnosis_3m"]."',
oasis_patient_diagnosis_4m='".$_POST["oasis_patient_diagnosis_4m"]."'
where id=$id");
}
$_SESSION["encounter"] = $encounter;
formHeader("Redirecting....");
formJump();
formFooter();

?>
