CREATE TABLE IF NOT EXISTS `forms_msw_visit_note` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,

msw_visit_note_time_in varchar(40),
msw_visit_note_time_out varchar(40),
msw_visit_note_date date default NULL,
msw_visit_note_patient_name varchar(40),
msw_visit_note_mr varchar(40),
msw_visit_note_soc date default NULL,
msw_visit_note_homebound_reason varchar(50),
msw_visit_note_homebound_reason_in varchar(100),
msw_visit_note_homebound_reason_other varchar(100),
msw_visit_note_phychological_health_environmental_situation text,
msw_visit_note_asssessment_of_current varchar(40),
msw_visit_note_asssessment_of_current_other text,
msw_visit_note_patient_education varchar(40),
msw_visit_note_patient_education_other text,
msw_visit_note_interventions_including text,
msw_visit_note_interventions_including_other text,
msw_visit_note_planning_and_organization text,
msw_visit_note_planning_and_organization_other text,
msw_visit_note_additional_comments text,
msw_visit_note_msw_visit_communicated_to varchar(40),
msw_visit_note_msw_visit_communicated_to_other text,
msw_visit_note_msw varchar(40)
) ENGINE=MyISAM;