CREATE TABLE IF NOT EXISTS `forms_st_Evaluation` (
id bigint(20) NOT NULL auto_increment primary key,
date datetime default NULL,
pid bigint(20) default NULL,
user varchar(255) default NULL,
groupname varchar(255) default NULL,
authorized tinyint(4) default NULL,
activity tinyint(4) default NULL,
mr varchar(40),
Evaluation_date date,
Evaluation_Pulse varchar(100),
Evaluation_Pulse_State varchar(40),
Evaluation_Temperature varchar(20),
Evaluation_Temperature_type varchar(40),
Evaluation_VS_other varchar(100),
Evaluation_VS_Respirations varchar(100),
Evaluation_VS_BP_Systolic varchar(40),
Evaluation_VS_BP_Diastolic varchar(40),
Evaluation_VS_BP_Body_side varchar(40),
Evaluation_VS_BP_Body_Position varchar(40),
Evaluation_VS_Sat varchar(40),
Evaluation_VS_Pain varchar(100),
Evaluation_VS_Pain_Intensity varchar(40),
Evaluation_VS_Location varchar(100),
Evaluation_VS_Other1 varchar(255),
Evaluation_HR_Needs_assistance varchar(10),
Evaluation_HR_Unable_to_leave_home varchar(10),
Evaluation_HR_Medical_Restrictions varchar(10),
Evaluation_HR_Medical_Restrictions_In varchar(100),
Evaluation_HR_SOB_upon_exertion varchar(10),
Evaluation_HR_Pain_with_Travel varchar(10),
Evaluation_HR_Requires_assistance varchar(10),
Evaluation_HR_Arrhythmia varchar(10),
Evaluation_HR_Bed_Bound varchar(10),
Evaluation_HR_Residual_Weakness varchar(10),
Evaluation_HR_Confusion varchar(10),
Evaluation_HR_Multiple_Stairs_Home varchar(10),
Evaluation_HR_Other varchar(255),
Evaluation_Reason_for_intervention varchar(255),
Evaluation_TREATMENT_DX_Problem varchar(255),
Evaluation_PERTINENT_MEDICAL_HISTORY text,
Evaluation_MEDICAL_FUNCTIONAL_PRECAUTIONS varchar(100),
Evaluation_MFP_Swallow_status varchar(40),
Evaluation_MFP_Other varchar(100),
Evaluation_MFP_Handedness varchar(30),
Evaluation_MFP_Limitations varchar(30),
Evaluation_MFP_Current_Weight_Loss varchar(30),
Evaluation_MFP_Weight_Loss_Reason text,
Evaluation_Prior_Level_Of_Function text,
Evaluation_Family_Caregiver_Support varchar(30),
Evaluation_Family_Caregiver_Support_Who varchar(50),
Evaluation_FC_Visits_Community_Weekly varchar(40),
Evaluation_FC_Additional_Comments varchar(255),
Evaluation_Auditory_Comp varchar(100),
Evaluation_Reading_Comp varchar(100),
Evaluation_Verbal_Expression varchar(100),
Evaluation_Written_Expression varchar(100),
Evaluation_Gestural_Expression varchar(100),
Evaluation_Speech_Intelligibility varchar(100),
Evaluation_Diet_Level varchar(100),
Evaluation_Mastication varchar(100),
Evaluation_Lingual_Transfer varchar(100),
Evaluation_Pocketing varchar(100),
Evaluation_AP_Propulsion varchar(100),
Evaluation_Oral_Transit varchar(100),
Evaluation_Swallow_Timing varchar(100),
Evaluation_Mental_Status varchar(30),
Evaluation_Mental_Status_Oriented_to varchar(30),
Evaluation_MS_Additional_Comments text,
Evaluation_ST_Evaluation_Only varchar(30),
Evaluation_Need_Physician_Orders varchar(30),
Evaluation_Received_Physician_Orders varchar(30),
Evaluation_Approximate_Next_Visit_Date date,
Evaluation_ST_Communicated_And_Agreed_by varchar(100),
Evaluation_ST_Communicated_And_Agreed_By_Other text,
Evaluation_ADDITIONAL_SERVICES_Speech_Excersice  varchar(100),
Evaluation_ADDITIONAL_SERVICES_Swallow_technique varchar(100),
Evaluation_ADDITIONAL_SERVICES_Diet_Modifications varchar(100),
Evaluation_ADDITIONAL_SERVICES_Treatment varchar(100),
Evaluation_ASP_Treatment_For text,
Evaluation_Skilled_ST_Necessary_To varchar(100),
Evaluation_Skilled_ST_Other text,
Evaluation_Therapist_Who_Developed_POC varchar(255)
) ENGINE=MyISAM;